In [12]:
randoms[0, 0:100].shape

(2,)

In [ ]:
arr = np.arange(10000000)
start = time.time()
arr_squared = arr ** 2
print("NumPy time:", time.time() - start)

NumPy time: 2.371973752975464


In [ ]:
import time

lst = list(range(10000000))
start = time.time()
lst_squared = [i**2 for i in lst]
print("Python list time:", time.time() - start)

In [5]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

b = np.array([[1, 2], [3, 4]])
print(b)

zeros = np.zeros((3,3))
ones = np.ones((2,4))
randoms = np.random.rand(2,2)

[1 2 3 4 5]
[[1 2]
 [3 4]]


In [9]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a[1:4])

(5,)
1
5
int64
[2 3 4]
